// Turns a report into the rows written to the Sheet or downloaded as CSV.

export const FELLOW_HEADER = [
  'Fellow Name', 'Email', 'Attendance', 'Minutes attended', 'Minutes missed',
  'Enrollment status', 'Zoom display name', 'How matched', 'Notes',
];

export const OTHER_HEADER = [
  'Zoom display name', 'Zoom email', 'Minutes in session', 'Status', 'Notes',
];

function fmtTime(d) {
  let h = d.getHours();
  const m = String(d.getMinutes()).padStart(2, '0');
  const ampm = h >= 12 ? 'PM' : 'AM';
  h = h % 12;
  if (h === 0) h = 12;
  return h + ':' + m + ' ' + ampm;
}

export function reportTitle(report) {
  return 'Attendance ' + report.session.date;
}

export function reportRows(report, meta = {}) {
  const rows = [];
  rows.push(FELLOW_HEADER);
  for (const f of report.fellows) {
    rows.push([
      f.person.name,
      f.person.email,
      f.attendance,
      f.attendedMinutes,
      f.missedMinutes,
      f.person.status,
      f.zoomNames.join('; '),
      f.matchMethod,
      f.notes.join(' '),
    ]);
  }

  rows.push([]);
  rows.push(['Zoom attendees not on the roster']);
  rows.push(OTHER_HEADER);
  if (report.others.length === 0) {
    rows.push(['(none)']);
  }
  for (const o of report.others) {
    rows.push([
      o.identity.name,
      o.identity.email,
      o.minutes,
      o.status,
      o.note,
    ]);
  }

  const s = report.summary;
  rows.push([]);
  rows.push(['Summary']);
  rows.push(['Session', report.session.date + ', ' + fmtTime(report.window.start) + ' to ' + fmtTime(report.window.end)]);
  rows.push(['Rule', 'Absent when more than ' + report.graceMinutes + ' minutes of the session were missed']);
  rows.push(['Present', s.present]);
  rows.push(['Absent', s.absent]);
  rows.push(['Not enrolled', s.notEnrolled]);
  rows.push(['Zoom entries needing review', s.needsReview]);
  rows.push(['Zoom entries not on the roster', s.notOnRoster]);
  rows.push(['Zoom rows ignored (different date)', s.offDateRows]);
  if (meta.fileName) rows.push(['Source file', meta.fileName]);
  if (meta.generatedAt) rows.push(['Generated', meta.generatedAt]);
  if (meta.generatedBy) rows.push(['Generated by', meta.generatedBy]);

  return rows;
}
